//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzhioFinans_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultAction
    {
        public int Id { get; set; }
        public int IdSotr { get; set; }
        public int IdAction { get; set; }
        public string Qwen { get; set; }
        public Nullable<int> Actual { get; set; }
    
        public virtual ConsultInvest ConsultInvest { get; set; }
        public virtual SellAction SellAction { get; set; }
    }
}
