//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzhioFinans_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultInvest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConsultInvest()
        {
            this.ConsultAction = new HashSet<ConsultAction>();
        }
    
        public int Id { get; set; }
        public string NamesurnameSotr { get; set; }
        public int IdUser { get; set; }
        public string PlaceInvest { get; set; }
        public int ActualInvest { get; set; }
        public string ColInvest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultAction> ConsultAction { get; set; }
        public virtual ManageProperty ManageProperty { get; set; }
    }
}
