//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzhioFinans_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageProperty
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public Nullable<int> TypeProp { get; set; }
        public string DateOfHouse { get; set; }
        public string DateOfFloor { get; set; }
        public string DedlineHouse { get; set; }
        public string DedlineFloor { get; set; }
        public string DateSellHouse { get; set; }
        public string DateSellFloor { get; set; }
    }
}
