//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzhioFinans_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AzhioFinans_ProjectEntities12 : DbContext
    {
        public AzhioFinans_ProjectEntities12()
            : base("name=AzhioFinans_ProjectEntities12")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autorization> Autorization { get; set; }
        public virtual DbSet<ConsultAction> ConsultAction { get; set; }
        public virtual DbSet<ConsultInvest> ConsultInvest { get; set; }
        public virtual DbSet<ManageProperty> ManageProperty { get; set; }
        public virtual DbSet<RentProperty> RentProperty { get; set; }
        public virtual DbSet<SellAction> SellAction { get; set; }
        public virtual DbSet<SellsAction> SellsAction { get; set; }
    }
}
