//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzhioFinans_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SellAction()
        {
            this.ConsultAction = new HashSet<ConsultAction>();
            this.SellsAction = new HashSet<SellsAction>();
        }
    
        public int Id { get; set; }
        public int IdUser { get; set; }
        public string DateSell { get; set; }
        public string PriceSell { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultAction> ConsultAction { get; set; }
        public virtual ManageProperty ManageProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellsAction> SellsAction { get; set; }
    }
}
